theme: jekyll-theme-leap-day
title: Tales from Skyrim's Holds
description: A visually Borderlands inspired Skyrim Overhaul Modlist 
show_downloads: true
wabbajack:
  wabbajack_url: https://www.wabbajack.org/#/
github:
  modlistrelases_url: https://github.com/EzioTheDeadPoet/Tales-from-Skyrims-Holds/releases
  modlist_url: https://github.com/EzioTheDeadPoet/Tales-from-Skyrims-Holds/releases/download/v1.0/Tales.from.Skyrim.s.Holds.wabbajack
pages:
  mainpage_url: https://eziothedeadpoet.github.io/Tales-from-Skyrims-Holds/
  screenshots_url: https://eziothedeadpoet.github.io/Tales-from-Skyrims-Holds/SCREENSHOTSDISPLAY.html
  contribute_url: https://eziothedeadpoet.github.io/Tales-from-Skyrims-Holds/HOWTOCONTRIBUTE.html
  changelog_url: https://eziothedeadpoet.github.io/Tales-from-Skyrims-Holds/CHANGELOG.html
reshade:
  license: https://eziothedeadpoet.github.io/Tales-from-Skyrims-Holds/ReShade/RESHADELICENSE.html
