theme: jekyll-theme-dinky
title: Tales from the Northern Lands
description: A visually Borderlands inspired Skyrim Overhaul Modlist, that aims to make the player feel more powerful trough the use of SPERG, Skyrim Skill Uncapper and the True Dragonborn preset for it.
show_downloads: true
wabbajack:
  wabbajack_url: https://www.wabbajack.org/#/
github:
  modlistrelases_url: https://github.com/EzioTheDeadPoet/Tales-from-the-Northern-Lands/releases
  modlist_url: https://github.com/EzioTheDeadPoet/Tales-from-the-Northern-Lands/releases/download/v1.0/Tales.from.Skyrim.s.Holds.wabbajack
pages:
  mainpage_url: https://eziothedeadpoet.github.io/Tales-from-the-Northern-Lands/
  screenshots_url: https://eziothedeadpoet.github.io/Tales-from-the-Northern-Lands/SCREENSHOTSDISPLAY.html
  contribute_url: https://eziothedeadpoet.github.io/Tales-from-the-Northern-Lands/HOWTOCONTRIBUTE.html
  changelog_url: https://eziothedeadpoet.github.io/Tales-from-the-Northern-Lands/CHANGELOG.html
reshade:
  license: https://eziothedeadpoet.github.io/Tales-from-the-Northern-Lands/ReShade/RESHADELICENSE.html
